name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instalar pnpm usando npm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      # 5. Configurar variables de entorno
      - name: Set up environment variables
        run: echo "POSTGRES_URL= postgres://default:6ZQLDNv3fFHW@ep-red-term-a4wde820-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"

      # 6. Construir el proyecto
      - name: Build project
        run: pnpm run build

      # 7. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_branch: gh-pages # Nombre de la rama de publicación
          allow_empty_commit: true
