name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # Habilitar caché para pnpm

      # 3. Instalar pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Instalar dependencias
      - name: Install dependencies
        run: pnpm install

      # 5. Construir el proyecto
      - name: Build project
        run: pnpm run build

      # 6. Exportar el proyecto (si es necesario)
      - name: Export project
        run: pnpm run export

      # 7. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Carpeta generada por 'next export'
